# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nary/egserv/src/mysub/eggsing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nary/egserv/src/mysub/eggsing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nary/egserv/src/mysub/eggsing/CMakeFiles /home/nary/egserv/src/mysub/eggsing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nary/egserv/src/mysub/eggsing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named im

# Build rule for target.
im: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 im
.PHONY : im

# fast build rule for target.
im/fast:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/build
.PHONY : im/fast

egnet/EgImConn.o: egnet/EgImConn.cpp.o
.PHONY : egnet/EgImConn.o

# target to build an object file
egnet/EgImConn.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/egnet/EgImConn.cpp.o
.PHONY : egnet/EgImConn.cpp.o

egnet/EgImConn.i: egnet/EgImConn.cpp.i
.PHONY : egnet/EgImConn.i

# target to preprocess a source file
egnet/EgImConn.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/egnet/EgImConn.cpp.i
.PHONY : egnet/EgImConn.cpp.i

egnet/EgImConn.s: egnet/EgImConn.cpp.s
.PHONY : egnet/EgImConn.s

# target to generate assembly for a file
egnet/EgImConn.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/egnet/EgImConn.cpp.s
.PHONY : egnet/EgImConn.cpp.s

egnet/EgIo.o: egnet/EgIo.cpp.o
.PHONY : egnet/EgIo.o

# target to build an object file
egnet/EgIo.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/egnet/EgIo.cpp.o
.PHONY : egnet/EgIo.cpp.o

egnet/EgIo.i: egnet/EgIo.cpp.i
.PHONY : egnet/EgIo.i

# target to preprocess a source file
egnet/EgIo.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/egnet/EgIo.cpp.i
.PHONY : egnet/EgIo.cpp.i

egnet/EgIo.s: egnet/EgIo.cpp.s
.PHONY : egnet/EgIo.s

# target to generate assembly for a file
egnet/EgIo.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/egnet/EgIo.cpp.s
.PHONY : egnet/EgIo.cpp.s

egnet/EgUtil.o: egnet/EgUtil.cpp.o
.PHONY : egnet/EgUtil.o

# target to build an object file
egnet/EgUtil.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/egnet/EgUtil.cpp.o
.PHONY : egnet/EgUtil.cpp.o

egnet/EgUtil.i: egnet/EgUtil.cpp.i
.PHONY : egnet/EgUtil.i

# target to preprocess a source file
egnet/EgUtil.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/egnet/EgUtil.cpp.i
.PHONY : egnet/EgUtil.cpp.i

egnet/EgUtil.s: egnet/EgUtil.cpp.s
.PHONY : egnet/EgUtil.s

# target to generate assembly for a file
egnet/EgUtil.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/egnet/EgUtil.cpp.s
.PHONY : egnet/EgUtil.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/main.cpp.s
.PHONY : main.cpp.s

third/src/jsoncpp/json_reader.o: third/src/jsoncpp/json_reader.cpp.o
.PHONY : third/src/jsoncpp/json_reader.o

# target to build an object file
third/src/jsoncpp/json_reader.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/jsoncpp/json_reader.cpp.o
.PHONY : third/src/jsoncpp/json_reader.cpp.o

third/src/jsoncpp/json_reader.i: third/src/jsoncpp/json_reader.cpp.i
.PHONY : third/src/jsoncpp/json_reader.i

# target to preprocess a source file
third/src/jsoncpp/json_reader.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/jsoncpp/json_reader.cpp.i
.PHONY : third/src/jsoncpp/json_reader.cpp.i

third/src/jsoncpp/json_reader.s: third/src/jsoncpp/json_reader.cpp.s
.PHONY : third/src/jsoncpp/json_reader.s

# target to generate assembly for a file
third/src/jsoncpp/json_reader.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/jsoncpp/json_reader.cpp.s
.PHONY : third/src/jsoncpp/json_reader.cpp.s

third/src/jsoncpp/json_value.o: third/src/jsoncpp/json_value.cpp.o
.PHONY : third/src/jsoncpp/json_value.o

# target to build an object file
third/src/jsoncpp/json_value.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/jsoncpp/json_value.cpp.o
.PHONY : third/src/jsoncpp/json_value.cpp.o

third/src/jsoncpp/json_value.i: third/src/jsoncpp/json_value.cpp.i
.PHONY : third/src/jsoncpp/json_value.i

# target to preprocess a source file
third/src/jsoncpp/json_value.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/jsoncpp/json_value.cpp.i
.PHONY : third/src/jsoncpp/json_value.cpp.i

third/src/jsoncpp/json_value.s: third/src/jsoncpp/json_value.cpp.s
.PHONY : third/src/jsoncpp/json_value.s

# target to generate assembly for a file
third/src/jsoncpp/json_value.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/jsoncpp/json_value.cpp.s
.PHONY : third/src/jsoncpp/json_value.cpp.s

third/src/jsoncpp/json_writer.o: third/src/jsoncpp/json_writer.cpp.o
.PHONY : third/src/jsoncpp/json_writer.o

# target to build an object file
third/src/jsoncpp/json_writer.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/jsoncpp/json_writer.cpp.o
.PHONY : third/src/jsoncpp/json_writer.cpp.o

third/src/jsoncpp/json_writer.i: third/src/jsoncpp/json_writer.cpp.i
.PHONY : third/src/jsoncpp/json_writer.i

# target to preprocess a source file
third/src/jsoncpp/json_writer.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/jsoncpp/json_writer.cpp.i
.PHONY : third/src/jsoncpp/json_writer.cpp.i

third/src/jsoncpp/json_writer.s: third/src/jsoncpp/json_writer.cpp.s
.PHONY : third/src/jsoncpp/json_writer.s

# target to generate assembly for a file
third/src/jsoncpp/json_writer.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/jsoncpp/json_writer.cpp.s
.PHONY : third/src/jsoncpp/json_writer.cpp.s

third/src/net/HttpClient.o: third/src/net/HttpClient.cpp.o
.PHONY : third/src/net/HttpClient.o

# target to build an object file
third/src/net/HttpClient.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/net/HttpClient.cpp.o
.PHONY : third/src/net/HttpClient.cpp.o

third/src/net/HttpClient.i: third/src/net/HttpClient.cpp.i
.PHONY : third/src/net/HttpClient.i

# target to preprocess a source file
third/src/net/HttpClient.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/net/HttpClient.cpp.i
.PHONY : third/src/net/HttpClient.cpp.i

third/src/net/HttpClient.s: third/src/net/HttpClient.cpp.s
.PHONY : third/src/net/HttpClient.s

# target to generate assembly for a file
third/src/net/HttpClient.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/net/HttpClient.cpp.s
.PHONY : third/src/net/HttpClient.cpp.s

third/src/protocol/IM.BaseDefine.pb.o: third/src/protocol/IM.BaseDefine.pb.cc.o
.PHONY : third/src/protocol/IM.BaseDefine.pb.o

# target to build an object file
third/src/protocol/IM.BaseDefine.pb.cc.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.BaseDefine.pb.cc.o
.PHONY : third/src/protocol/IM.BaseDefine.pb.cc.o

third/src/protocol/IM.BaseDefine.pb.i: third/src/protocol/IM.BaseDefine.pb.cc.i
.PHONY : third/src/protocol/IM.BaseDefine.pb.i

# target to preprocess a source file
third/src/protocol/IM.BaseDefine.pb.cc.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.BaseDefine.pb.cc.i
.PHONY : third/src/protocol/IM.BaseDefine.pb.cc.i

third/src/protocol/IM.BaseDefine.pb.s: third/src/protocol/IM.BaseDefine.pb.cc.s
.PHONY : third/src/protocol/IM.BaseDefine.pb.s

# target to generate assembly for a file
third/src/protocol/IM.BaseDefine.pb.cc.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.BaseDefine.pb.cc.s
.PHONY : third/src/protocol/IM.BaseDefine.pb.cc.s

third/src/protocol/IM.Buddy.pb.o: third/src/protocol/IM.Buddy.pb.cc.o
.PHONY : third/src/protocol/IM.Buddy.pb.o

# target to build an object file
third/src/protocol/IM.Buddy.pb.cc.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Buddy.pb.cc.o
.PHONY : third/src/protocol/IM.Buddy.pb.cc.o

third/src/protocol/IM.Buddy.pb.i: third/src/protocol/IM.Buddy.pb.cc.i
.PHONY : third/src/protocol/IM.Buddy.pb.i

# target to preprocess a source file
third/src/protocol/IM.Buddy.pb.cc.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Buddy.pb.cc.i
.PHONY : third/src/protocol/IM.Buddy.pb.cc.i

third/src/protocol/IM.Buddy.pb.s: third/src/protocol/IM.Buddy.pb.cc.s
.PHONY : third/src/protocol/IM.Buddy.pb.s

# target to generate assembly for a file
third/src/protocol/IM.Buddy.pb.cc.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Buddy.pb.cc.s
.PHONY : third/src/protocol/IM.Buddy.pb.cc.s

third/src/protocol/IM.File.pb.o: third/src/protocol/IM.File.pb.cc.o
.PHONY : third/src/protocol/IM.File.pb.o

# target to build an object file
third/src/protocol/IM.File.pb.cc.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.File.pb.cc.o
.PHONY : third/src/protocol/IM.File.pb.cc.o

third/src/protocol/IM.File.pb.i: third/src/protocol/IM.File.pb.cc.i
.PHONY : third/src/protocol/IM.File.pb.i

# target to preprocess a source file
third/src/protocol/IM.File.pb.cc.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.File.pb.cc.i
.PHONY : third/src/protocol/IM.File.pb.cc.i

third/src/protocol/IM.File.pb.s: third/src/protocol/IM.File.pb.cc.s
.PHONY : third/src/protocol/IM.File.pb.s

# target to generate assembly for a file
third/src/protocol/IM.File.pb.cc.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.File.pb.cc.s
.PHONY : third/src/protocol/IM.File.pb.cc.s

third/src/protocol/IM.Group.pb.o: third/src/protocol/IM.Group.pb.cc.o
.PHONY : third/src/protocol/IM.Group.pb.o

# target to build an object file
third/src/protocol/IM.Group.pb.cc.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Group.pb.cc.o
.PHONY : third/src/protocol/IM.Group.pb.cc.o

third/src/protocol/IM.Group.pb.i: third/src/protocol/IM.Group.pb.cc.i
.PHONY : third/src/protocol/IM.Group.pb.i

# target to preprocess a source file
third/src/protocol/IM.Group.pb.cc.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Group.pb.cc.i
.PHONY : third/src/protocol/IM.Group.pb.cc.i

third/src/protocol/IM.Group.pb.s: third/src/protocol/IM.Group.pb.cc.s
.PHONY : third/src/protocol/IM.Group.pb.s

# target to generate assembly for a file
third/src/protocol/IM.Group.pb.cc.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Group.pb.cc.s
.PHONY : third/src/protocol/IM.Group.pb.cc.s

third/src/protocol/IM.Login.pb.o: third/src/protocol/IM.Login.pb.cc.o
.PHONY : third/src/protocol/IM.Login.pb.o

# target to build an object file
third/src/protocol/IM.Login.pb.cc.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Login.pb.cc.o
.PHONY : third/src/protocol/IM.Login.pb.cc.o

third/src/protocol/IM.Login.pb.i: third/src/protocol/IM.Login.pb.cc.i
.PHONY : third/src/protocol/IM.Login.pb.i

# target to preprocess a source file
third/src/protocol/IM.Login.pb.cc.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Login.pb.cc.i
.PHONY : third/src/protocol/IM.Login.pb.cc.i

third/src/protocol/IM.Login.pb.s: third/src/protocol/IM.Login.pb.cc.s
.PHONY : third/src/protocol/IM.Login.pb.s

# target to generate assembly for a file
third/src/protocol/IM.Login.pb.cc.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Login.pb.cc.s
.PHONY : third/src/protocol/IM.Login.pb.cc.s

third/src/protocol/IM.Message.pb.o: third/src/protocol/IM.Message.pb.cc.o
.PHONY : third/src/protocol/IM.Message.pb.o

# target to build an object file
third/src/protocol/IM.Message.pb.cc.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Message.pb.cc.o
.PHONY : third/src/protocol/IM.Message.pb.cc.o

third/src/protocol/IM.Message.pb.i: third/src/protocol/IM.Message.pb.cc.i
.PHONY : third/src/protocol/IM.Message.pb.i

# target to preprocess a source file
third/src/protocol/IM.Message.pb.cc.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Message.pb.cc.i
.PHONY : third/src/protocol/IM.Message.pb.cc.i

third/src/protocol/IM.Message.pb.s: third/src/protocol/IM.Message.pb.cc.s
.PHONY : third/src/protocol/IM.Message.pb.s

# target to generate assembly for a file
third/src/protocol/IM.Message.pb.cc.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Message.pb.cc.s
.PHONY : third/src/protocol/IM.Message.pb.cc.s

third/src/protocol/IM.Other.pb.o: third/src/protocol/IM.Other.pb.cc.o
.PHONY : third/src/protocol/IM.Other.pb.o

# target to build an object file
third/src/protocol/IM.Other.pb.cc.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Other.pb.cc.o
.PHONY : third/src/protocol/IM.Other.pb.cc.o

third/src/protocol/IM.Other.pb.i: third/src/protocol/IM.Other.pb.cc.i
.PHONY : third/src/protocol/IM.Other.pb.i

# target to preprocess a source file
third/src/protocol/IM.Other.pb.cc.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Other.pb.cc.i
.PHONY : third/src/protocol/IM.Other.pb.cc.i

third/src/protocol/IM.Other.pb.s: third/src/protocol/IM.Other.pb.cc.s
.PHONY : third/src/protocol/IM.Other.pb.s

# target to generate assembly for a file
third/src/protocol/IM.Other.pb.cc.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Other.pb.cc.s
.PHONY : third/src/protocol/IM.Other.pb.cc.s

third/src/protocol/IM.Server.pb.o: third/src/protocol/IM.Server.pb.cc.o
.PHONY : third/src/protocol/IM.Server.pb.o

# target to build an object file
third/src/protocol/IM.Server.pb.cc.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Server.pb.cc.o
.PHONY : third/src/protocol/IM.Server.pb.cc.o

third/src/protocol/IM.Server.pb.i: third/src/protocol/IM.Server.pb.cc.i
.PHONY : third/src/protocol/IM.Server.pb.i

# target to preprocess a source file
third/src/protocol/IM.Server.pb.cc.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Server.pb.cc.i
.PHONY : third/src/protocol/IM.Server.pb.cc.i

third/src/protocol/IM.Server.pb.s: third/src/protocol/IM.Server.pb.cc.s
.PHONY : third/src/protocol/IM.Server.pb.s

# target to generate assembly for a file
third/src/protocol/IM.Server.pb.cc.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.Server.pb.cc.s
.PHONY : third/src/protocol/IM.Server.pb.cc.s

third/src/protocol/IM.SwitchService.pb.o: third/src/protocol/IM.SwitchService.pb.cc.o
.PHONY : third/src/protocol/IM.SwitchService.pb.o

# target to build an object file
third/src/protocol/IM.SwitchService.pb.cc.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.SwitchService.pb.cc.o
.PHONY : third/src/protocol/IM.SwitchService.pb.cc.o

third/src/protocol/IM.SwitchService.pb.i: third/src/protocol/IM.SwitchService.pb.cc.i
.PHONY : third/src/protocol/IM.SwitchService.pb.i

# target to preprocess a source file
third/src/protocol/IM.SwitchService.pb.cc.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.SwitchService.pb.cc.i
.PHONY : third/src/protocol/IM.SwitchService.pb.cc.i

third/src/protocol/IM.SwitchService.pb.s: third/src/protocol/IM.SwitchService.pb.cc.s
.PHONY : third/src/protocol/IM.SwitchService.pb.s

# target to generate assembly for a file
third/src/protocol/IM.SwitchService.pb.cc.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/protocol/IM.SwitchService.pb.cc.s
.PHONY : third/src/protocol/IM.SwitchService.pb.cc.s

third/src/util/Lock.o: third/src/util/Lock.cpp.o
.PHONY : third/src/util/Lock.o

# target to build an object file
third/src/util/Lock.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/Lock.cpp.o
.PHONY : third/src/util/Lock.cpp.o

third/src/util/Lock.i: third/src/util/Lock.cpp.i
.PHONY : third/src/util/Lock.i

# target to preprocess a source file
third/src/util/Lock.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/Lock.cpp.i
.PHONY : third/src/util/Lock.cpp.i

third/src/util/Lock.s: third/src/util/Lock.cpp.s
.PHONY : third/src/util/Lock.s

# target to generate assembly for a file
third/src/util/Lock.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/Lock.cpp.s
.PHONY : third/src/util/Lock.cpp.s

third/src/util/Thread.o: third/src/util/Thread.cpp.o
.PHONY : third/src/util/Thread.o

# target to build an object file
third/src/util/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/Thread.cpp.o
.PHONY : third/src/util/Thread.cpp.o

third/src/util/Thread.i: third/src/util/Thread.cpp.i
.PHONY : third/src/util/Thread.i

# target to preprocess a source file
third/src/util/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/Thread.cpp.i
.PHONY : third/src/util/Thread.cpp.i

third/src/util/Thread.s: third/src/util/Thread.cpp.s
.PHONY : third/src/util/Thread.s

# target to generate assembly for a file
third/src/util/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/Thread.cpp.s
.PHONY : third/src/util/Thread.cpp.s

third/src/util/ThreadPool.o: third/src/util/ThreadPool.cpp.o
.PHONY : third/src/util/ThreadPool.o

# target to build an object file
third/src/util/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/ThreadPool.cpp.o
.PHONY : third/src/util/ThreadPool.cpp.o

third/src/util/ThreadPool.i: third/src/util/ThreadPool.cpp.i
.PHONY : third/src/util/ThreadPool.i

# target to preprocess a source file
third/src/util/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/ThreadPool.cpp.i
.PHONY : third/src/util/ThreadPool.cpp.i

third/src/util/ThreadPool.s: third/src/util/ThreadPool.cpp.s
.PHONY : third/src/util/ThreadPool.s

# target to generate assembly for a file
third/src/util/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/ThreadPool.cpp.s
.PHONY : third/src/util/ThreadPool.cpp.s

third/src/util/UtilPdu.o: third/src/util/UtilPdu.cpp.o
.PHONY : third/src/util/UtilPdu.o

# target to build an object file
third/src/util/UtilPdu.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/UtilPdu.cpp.o
.PHONY : third/src/util/UtilPdu.cpp.o

third/src/util/UtilPdu.i: third/src/util/UtilPdu.cpp.i
.PHONY : third/src/util/UtilPdu.i

# target to preprocess a source file
third/src/util/UtilPdu.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/UtilPdu.cpp.i
.PHONY : third/src/util/UtilPdu.cpp.i

third/src/util/UtilPdu.s: third/src/util/UtilPdu.cpp.s
.PHONY : third/src/util/UtilPdu.s

# target to generate assembly for a file
third/src/util/UtilPdu.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/UtilPdu.cpp.s
.PHONY : third/src/util/UtilPdu.cpp.s

third/src/util/util.o: third/src/util/util.cpp.o
.PHONY : third/src/util/util.o

# target to build an object file
third/src/util/util.cpp.o:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/util.cpp.o
.PHONY : third/src/util/util.cpp.o

third/src/util/util.i: third/src/util/util.cpp.i
.PHONY : third/src/util/util.i

# target to preprocess a source file
third/src/util/util.cpp.i:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/util.cpp.i
.PHONY : third/src/util/util.cpp.i

third/src/util/util.s: third/src/util/util.cpp.s
.PHONY : third/src/util/util.s

# target to generate assembly for a file
third/src/util/util.cpp.s:
	$(MAKE) -f CMakeFiles/im.dir/build.make CMakeFiles/im.dir/third/src/util/util.cpp.s
.PHONY : third/src/util/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... im"
	@echo "... rebuild_cache"
	@echo "... egnet/EgImConn.o"
	@echo "... egnet/EgImConn.i"
	@echo "... egnet/EgImConn.s"
	@echo "... egnet/EgIo.o"
	@echo "... egnet/EgIo.i"
	@echo "... egnet/EgIo.s"
	@echo "... egnet/EgUtil.o"
	@echo "... egnet/EgUtil.i"
	@echo "... egnet/EgUtil.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... third/src/jsoncpp/json_reader.o"
	@echo "... third/src/jsoncpp/json_reader.i"
	@echo "... third/src/jsoncpp/json_reader.s"
	@echo "... third/src/jsoncpp/json_value.o"
	@echo "... third/src/jsoncpp/json_value.i"
	@echo "... third/src/jsoncpp/json_value.s"
	@echo "... third/src/jsoncpp/json_writer.o"
	@echo "... third/src/jsoncpp/json_writer.i"
	@echo "... third/src/jsoncpp/json_writer.s"
	@echo "... third/src/net/HttpClient.o"
	@echo "... third/src/net/HttpClient.i"
	@echo "... third/src/net/HttpClient.s"
	@echo "... third/src/protocol/IM.BaseDefine.pb.o"
	@echo "... third/src/protocol/IM.BaseDefine.pb.i"
	@echo "... third/src/protocol/IM.BaseDefine.pb.s"
	@echo "... third/src/protocol/IM.Buddy.pb.o"
	@echo "... third/src/protocol/IM.Buddy.pb.i"
	@echo "... third/src/protocol/IM.Buddy.pb.s"
	@echo "... third/src/protocol/IM.File.pb.o"
	@echo "... third/src/protocol/IM.File.pb.i"
	@echo "... third/src/protocol/IM.File.pb.s"
	@echo "... third/src/protocol/IM.Group.pb.o"
	@echo "... third/src/protocol/IM.Group.pb.i"
	@echo "... third/src/protocol/IM.Group.pb.s"
	@echo "... third/src/protocol/IM.Login.pb.o"
	@echo "... third/src/protocol/IM.Login.pb.i"
	@echo "... third/src/protocol/IM.Login.pb.s"
	@echo "... third/src/protocol/IM.Message.pb.o"
	@echo "... third/src/protocol/IM.Message.pb.i"
	@echo "... third/src/protocol/IM.Message.pb.s"
	@echo "... third/src/protocol/IM.Other.pb.o"
	@echo "... third/src/protocol/IM.Other.pb.i"
	@echo "... third/src/protocol/IM.Other.pb.s"
	@echo "... third/src/protocol/IM.Server.pb.o"
	@echo "... third/src/protocol/IM.Server.pb.i"
	@echo "... third/src/protocol/IM.Server.pb.s"
	@echo "... third/src/protocol/IM.SwitchService.pb.o"
	@echo "... third/src/protocol/IM.SwitchService.pb.i"
	@echo "... third/src/protocol/IM.SwitchService.pb.s"
	@echo "... third/src/util/Lock.o"
	@echo "... third/src/util/Lock.i"
	@echo "... third/src/util/Lock.s"
	@echo "... third/src/util/Thread.o"
	@echo "... third/src/util/Thread.i"
	@echo "... third/src/util/Thread.s"
	@echo "... third/src/util/ThreadPool.o"
	@echo "... third/src/util/ThreadPool.i"
	@echo "... third/src/util/ThreadPool.s"
	@echo "... third/src/util/UtilPdu.o"
	@echo "... third/src/util/UtilPdu.i"
	@echo "... third/src/util/UtilPdu.s"
	@echo "... third/src/util/util.o"
	@echo "... third/src/util/util.i"
	@echo "... third/src/util/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

